[[main]]
identifier = "about"
name = "Sobre"
url = "about"
weight = 1

[[main]]
identifier = "posts"
name = "Posts"
url = "posts"
weight = 2

[[main]]
identifier = "archive"
name = "Arquivo"
url = "archive"
weight = 3

[[main]]
identifier = "showcase"
name = "Projetos"
url = "showcase"
weight = 4
