baseurl = "/"
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
paginate = 5
title = "Flads"
description = "Cristão, Programador e Comedor de Camarão..."
tags = ["flads", "fabio lucas", "cristão", "programador", "comedor de camarão"]
theme = "hyde"
summaryLength = 25

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/flads"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/fabio-lucas/"}
  ]

[params]
  description = "Cristão, Programador e Comedor de Camarão..."
  themeColor = "theme-base-color"

