baseurl = "/"
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
paginate = 5
title = "Flads"
description = "Web Developer"
tags = ["flads", "fabio lucas"]
theme = "hyde"
summaryLength = 25

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/flads"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/fabio-lucas/"},
      {Name = "Contrate-me", URL = "https://www.flads.com.br"}
  ]

[params]
  description = "Web Developer"
  themeColor = "theme-base-color"

